---
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart auditd
  command: service auditd restart

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
